# Generated by Django 2.2.2 on 2019-06-11 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tagent_leave_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_ids', to='tagent_leave_app.Employee'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(default='New', max_length=50),
        ),
    ]
